import { TestBed } from '@angular/core/testing';
import { ActivatedRoute, convertToParamMap, provideRouter, Router } from '@angular/router';
import { NEVER, of, throwError } from 'rxjs';
import { SessionService } from '../../core/session.service';
import { Execution } from './execution.models';
import { ExecutionDetailComponent } from './execution-detail.component';
import { ExecutionService } from './execution.service';

describe('ExecutionDetailComponent',()=>{
 const execution:Execution={execution_id:'exec-1',status:'completed_with_errors',lifecycle:'partial',attempt:1,source:'N-FP',reprocessed_from_execution_id:null,started_at:'2026-01-01T00:00:00Z',finished_at:'2026-01-01T00:01:00Z',failure_reason:null,pipeline_version:'1',rule_catalog_version:'1',state_version:2,state_history:[{from_state:'processing',to_state:'completed_with_errors',reason:'partial',state_version:2,occurred_at:'2026-01-01T00:01:00Z'}],counts:{files:1,files_received:1,files_accepted:1,files_rejected:0,rows_read:2,valid_records:1,rejected_records:1,normalized_records:1,workorders:1,lots:0,serials:0,classifications:1,pending_items:1,errors:1,warnings:0}};
 const api={get:jasmine.createSpy().and.returnValue(of(execution)),divergences:jasmine.createSpy().and.returnValue(of({items:[],pagination:{page:1,page_size:20,total:0,pages:0},sort:'oldest'})),classifications:jasmine.createSpy().and.returnValue(NEVER),pending:jasmine.createSpy().and.returnValue(NEVER),evidences:jasmine.createSpy().and.returnValue(NEVER),download:jasmine.createSpy().and.returnValue(NEVER),reprocess:jasmine.createSpy().and.returnValue(of({execution_id:'exec-2'}))};
 let permissions:string[];
 beforeEach(async()=>{permissions=['execution.read','artifact.read','artifact.export','execution.reprocess'];Object.values(api).forEach(spy=>spy.calls.reset());api.get.and.returnValue(of(execution));api.divergences.and.returnValue(of({items:[],pagination:{page:1,page_size:20,total:0,pages:0},sort:'oldest'}));api.reprocess.and.returnValue(of({execution_id:'exec-2'}));await TestBed.configureTestingModule({imports:[ExecutionDetailComponent],providers:[provideRouter([]),{provide:ActivatedRoute,useValue:{snapshot:{paramMap:convertToParamMap({executionId:'exec-1'}),queryParamMap:convertToParamMap({tab:'history'})}}},{provide:ExecutionService,useValue:api},{provide:SessionService,useValue:{hasPermission:(key:string)=>permissions.includes(key)}}]}).compileComponents();});
 it('distinguishes persisted state, partial lifecycle and chronological history',()=>{const fixture=TestBed.createComponent(ExecutionDetailComponent);fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('Execução concluída parcialmente');expect(fixture.nativeElement.textContent).toContain('completed_with_errors');expect(fixture.nativeElement.textContent).toContain('partial');});
 it('preserves the selected tab and filters in the URL',()=>{const router=TestBed.inject(Router);const navigate=spyOn(router,'navigate').and.resolveTo(true);const fixture=TestBed.createComponent(ExecutionDetailComponent);fixture.detectChanges();const component=fixture.componentInstance;component.severity.set('warning');component.source.set('OWM');component.selectTab('divergences');expect(navigate).toHaveBeenCalledWith([],jasmine.objectContaining({queryParams:{tab:'divergences',page:1,severity:'warning',source:'OWM'},queryParamsHandling:'merge',replaceUrl:true}));expect(api.divergences).toHaveBeenCalledWith('exec-1',1,'warning','OWM');});
 it('hides restricted tabs and actions',()=>{permissions=['execution.read'];const fixture=TestBed.createComponent(ExecutionDetailComponent);fixture.detectChanges();const component=fixture.componentInstance;expect(component.visibleTabs()).not.toContain('evidences');expect(component.visibleTabs()).not.toContain('divergences');expect(component.canReprocess()).toBeFalse();expect(component.canDownload()).toBeFalse();});
 it('reports API authorization and availability failures',()=>{api.get.and.returnValue(throwError(()=>({kind:'forbidden',status:403,code:'access_denied',message:'denied',correlationId:null,fields:[]})));const fixture=TestBed.createComponent(ExecutionDetailComponent);fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('denied');});
 it('creates a new execution without replacing the original',()=>{const component=TestBed.createComponent(ExecutionDetailComponent).componentInstance;component.ngOnInit();component.reprocess();expect(api.reprocess).toHaveBeenCalledWith('exec-1','web-execution-monitor');expect(component.reprocessedId()).toBe('exec-2');expect(component.item()?.execution_id).toBe('exec-1');});
});
